// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfC4PgN2I7q-BcRTvpH0-GTUgzf8bcnac',
    appId: '1:913157397362:web:962eb115878c0bd3e99beb',
    messagingSenderId: '913157397362',
    projectId: 'mathquiz-424403',
    authDomain: 'mathquiz-424403.firebaseapp.com',
    storageBucket: 'mathquiz-424403.appspot.com',
    measurementId: 'G-FCXBTD5JK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ50TOYm6qnMouhApWAJDn12PfsEW-KTc',
    appId: '1:913157397362:android:af155f280d814106e99beb',
    messagingSenderId: '913157397362',
    projectId: 'mathquiz-424403',
    storageBucket: 'mathquiz-424403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUNS5fZfYJXJoybkytSSNofHmOQmTwaNM',
    appId: '1:913157397362:ios:46ed6d065fe4f5cde99beb',
    messagingSenderId: '913157397362',
    projectId: 'mathquiz-424403',
    storageBucket: 'mathquiz-424403.appspot.com',
    iosClientId: '913157397362-hhc95nmflf31vem7nvno3pc39pflcfso.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathquizMobile',
  );

}