// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWy6LSlFDzBLrgEaj0aX0tF8kTumMAUq4',
    appId: '1:536358771254:web:e55e8c6d25c3fc26b11697',
    messagingSenderId: '536358771254',
    projectId: 'mathquiz-release',
    authDomain: 'mathquiz-release.firebaseapp.com',
    storageBucket: 'mathquiz-release.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoTLR2L-RI8pcque6Wl9_5kN1XZtiG6gM',
    appId: '1:536358771254:android:b4d175e20fc72198b11697',
    messagingSenderId: '536358771254',
    projectId: 'mathquiz-release',
    storageBucket: 'mathquiz-release.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJIwbw_AvSm-eRG4aXHqCKy1zZjKOnLmw',
    appId: '1:536358771254:ios:dcff771d1cae1b50b11697',
    messagingSenderId: '536358771254',
    projectId: 'mathquiz-release',
    storageBucket: 'mathquiz-release.appspot.com',
    androidClientId: '536358771254-tf1jsg78v0v8vip0g0749lohggfoqq4p.apps.googleusercontent.com',
    iosClientId: '536358771254-m0v393gssddn2bfsckshlvkcculpfhcf.apps.googleusercontent.com',
    iosBundleId: 'com.zafus.mathquiz',
  );

}